# Build settings
theme: minima

plugins:
  - jekyll-relative-links # converts links to markdown files to their html counterparts
  - jekyll-scholar

relative_links:
  enabled: true
  collections: true

markdown: kramdown
kramdown:
  math_engine: mathjax  # This enables LaTeX rendering

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
# - jekyll-remote-theme

title: "Pallab Dutta"
description: "Personal website of Pallab Dutta"

# logo: PallabDutta_Photo.jpg

header_pages:
  - index.md
  - research-blogs.md
  - publications.md
  - puzzles.md
  - projects.md
  - arts.md

scholar:
  style: apa         # Or another style like ieee, harvard-cite-them-right, etc.
  locale: en         # Language for localized terms (e.g., "Eds.")
  source: ./assets # Path where your .bib file(s) are stored (relative to root)
  bibliography: references.bib # Default .bib file name
  order: descending  # Sort order
  sort_by: year      # Field to sort by

#footer: false
